# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a110a6c5542fc0d67ac1fd795ab6a71415707c6763c84c1c11a7def820a70048724aa233a8ab871399525b037cfada655c9ed3e0200ae426eeeaea017c0c40f

test:
  secret_key_base: 37c5b441bad5d5cbfcc420a71569d815a4a6a3bafa8d88262e54727751ade09b4b97bbb3c0c87acbc1a018a231c8ef1a987dde724964d9d2730f93c5132092c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
